### ISSUE TITLE
Getting error: ❗️Uncaught TypeError: Cannot read properties of undefined (reading 'code') when running the the application localy

### ISSUE THREAD

**Issue by gopalanand333** [cap-js/telemetry#91]
Hi Team, 
I have installed the plugin version "0.0.3". When i am running the command cds watch, i am getting the following error 
```

[cds] - ❗️Uncaught TypeError: Cannot read properties of undefined (reading 'code')
    at onDone (/home/user/projects/incidents-app/node_modules/@cap-js/telemetry/lib/tracing/trace.js:229:23)
    at <anonymous>
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
TypeError: Cannot read properties of undefined (reading 'code')
    at onDone (/home/user/projects/incidents-app/node_modules/@cap-js/telemetry/lib/tracing/trace.js:229:23)
    at /home/user/projects/incidents-app/node_modules/@cap-js/telemetry/lib/tracing/trace.js:239:7
    at NoopContextManager.with (/home/user/projects/incidents-app/node_modules/@cap-js/telemetry/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:25:19)
    at ContextAPI.with (/home/user/projects/incidents-app/node_modules/@cap-js/telemetry/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
    at trace (/home/user/projects/incidents-app/node_modules/@cap-js/telemetry/lib/tracing/trace.js:218:27)
    at OKRAService.process (/home/user/projects/incidents-app/node_modules/@cap-js/telemetry/lib/tracing/okra.js:33:12)
    at OData.process (/home/user/projects/incidents-app/node_modules/@sap/cds/libx/_runtime/cds-services/adapter/odata-v4/OData.js:264:24)
    at Layer.handle [as handle_request] (/home/user/projects/incidents-app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/user/projects/incidents-app/node_modules/express/lib/router/index.js:328:13)
    at /home/user/projects/incidents-app/node_modules/express/lib/router/index.js:286:9
    
```
   Not sure if it's the app or framework. 
   
   | incidents |https://github.com/cap-js/incidents-app |
|:---------------------- | ----------- |
| Node.js                | v18.14.2    |
| @sap/cds               | 7.6.1       |
| @sap/cds-compiler      | 4.5.0       |
| @sap/cds-dk            | 7.5.0       |
| @sap/cds-dk (global)   | 7.5.1       |
| @sap/eslint-plugin-cds | 2.6.4       |
| @sap/cds-mtxs          | 1.14.0      |

**Comment by gopalanand333** [comment]
Another error:
```
[telemetry] - Error: @opentelemetry/api: Registration of version v1.7.0 for trace does not match previously registered API v1.4.1
    at registerGlobal (/home/user/projects/incidents-app/node_modules/@opentelemetry/api/build/src/internal/global-utils.js:38:21)
    at TraceAPI.setGlobalTracerProvider (/home/user/projects/incidents-app/node_modules/@opentelemetry/api/build/src/api/trace.js:54:59)
    at NodeTracerProvider.register (/home/user/projects/incidents-app/node_modules/@opentelemetry/sdk-trace-base/build/src/BasicTracerProvider.js:92:21)
    at NodeTracerProvider.register (/home/user/projects/incidents-app/node_modules/@opentelemetry/sdk-trace-node/build/src/NodeTracerProvider.js:43:15)
    at module.exports (/home/user/projects/incidents-app/node_modules/@cap-js/telemetry/lib/tracing/index.js:119:18)
    at module.exports (/home/user/projects/incidents-app/node_modules/@cap-js/telemetry/lib/index.js:22:3)
    at Object.<anonymous> (/home/user/projects/incidents-app/node_modules/@cap-js/telemetry/cds-plugin.js:1:48)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
```

**Comment by sjvans** [comment]
hi @gopalanand333 

i don't encounter these errors. please provide steps to reproduce.

thanks,
sebastian

**Comment by pankajinnitk** [comment]
@sjvans : We get the same error (❗️Uncaught TypeError: Cannot read properties of undefined (reading 'code')) in our apps for which we have set up a call with you for today. For us this is not reproducible in our local

**Comment by sjvans** [comment]
with fresh node_modules, the issue doesn't occur anymore

**Comment by pankajinnitk** [comment]
Hi @sjvans ,

This problem is still reproducible for our multiple apps. We have also upgraded our otel libraries which did not help.
Please find more more details which may be helpful for you to fix the same .
This problem seems to occur for missing handling for the traces which are marked as non recording by the sampler.
This will only occur if the trace is marked as non recording and hence it did not occur in localhost for us.
In case you want to reproduce in localhost you can change one of the spans for $batch call in localhost 
node_modules/@opentelemetry/sdk-trace-base/build/src/Tracer.js -> line no 88. In debug set the samplingResult.decision to 0 i.e. NOT_RECORD .

Post this when the call will reach 
node_modules/@cap-js/telemetry/lib/tracing/trace.js line no 229 , it will result in exception as such Non Recording spans do not have status in them.

<img width="1552" alt="image" src="https://github.com/cap-js/telemetry/assets/29799008/dec827c5-b456-4ba3-aca2-2abd4dff4906">

<img width="1658" alt="image" src="https://github.com/cap-js/telemetry/assets/29799008/a8fe32d5-bacd-444a-861e-10aa904a1441">

Hope these details help you fix the problem

Regards,
Pankaj
